# Generated by Django 5.1.2 on 2024-10-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(upload_to='media/auctions/%Y/%m/%d/'),
        ),
    ]
